name: mnjz_task
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_countdown_timer: ^4.1.0
  gradient_icon: ^2.0.8
  go_router: ^12.1.1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  arabic_numbers: ^1.0.0
  intl: ^0.18.1
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  google_fonts: ^6.1.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.1.2
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  sqflite: ^2.3.0
  dartz: ^0.10.1
  geolocator: ^10.1.0
  shimmer: ^3.0.0
  modal_bottom_sheet: ^3.0.0-pre


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
